image: pnavaro/pandoc

pages:
  stage: deploy
  script:
    - make
    - mkdir -p public
    - make html
    - mv synthese_2020.pdf public/
    - /home/euler/.local/bin/jupyter-book build .                                                          
    - mv _build/html public/new

  tags:
    - pandoc
  artifacts:
    paths:
      - public
