image: pnavaro/pandoc

pdf:
  stage: build
  script:
    - make
  tags:
    - pandoc, docker
  artifacts:
    paths:
      - "synthese_2020.pdf"

pages:
  stage: deploy
  script:
    - make html
  tags:
    - pandoc, docker
  artifacts:
    paths:
      - public
