image: pnavaro/pandoc

pages:
  stage: deploy
  script:
    - python3 -m pip install --user mkdocs-material
    - make
    - mkdir -p public
    - make html
    - cp synthese_2020.pdf public/
  tags:
    - pandoc
  artifacts:
    paths:
      - public
