image: pnavaro/pandoc

pages:
  stage: deploy
  script:
    - make
    - mkdir -p public
    - make html
    - cp synthese_2020.pdf public/
    - python3 -m pip install jupyter-book
    - jupyter-book build .                                                          
    - mv _build/html public/new

  tags:
    - pandoc
  artifacts:
    paths:
      - public
