image: pnavaro/pandoc

pages:
  stage: deploy
  script:
    - make
    - mkdir -p public
    - cp synthese_2020.pdf public/
    - make html
  tags:
    - pandoc
  artifacts:
    paths:
      - public
