image: pnavaro/pandoc

pages:
  stage: deploy
  script:
    - rm -rf public
    - make
    - mv synthese_2020.pdf public/
    - make book
    - make html

  tags:
    - pandoc
  artifacts:
    paths:
      - public
