image: pnavaro/pandoc

default:
  before_script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - pip3 install jupyter-book

html:
   stage: build
   script: jupyter-book build .                                                                    
   tags:
     - docker

latex:
   stage: build
   script: jupyter-book build . --builder pdflatex                                                 
   tags:
     - docker

linkcheck:
   stage: test
   script: jupyter-book build . --builder linkcheck                                                 
   allow_failure: true
   tags:
     - docker

pages:
  stage: deploy
  script:
    - mv _build/html public                                                                   
    - mv _build/latex/guide_bonnes_pratiques_gestion_donnees_recherche_v1.pdf public/
  tags:
    - docker
  artifacts:
    paths:
      - public
  only:
    - master
