image: pnavaro/pandoc

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

default:
  before_script:
    - python3 -m venv venv
    - source venv/bin/activate
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - pip install -U jupyter-book

html:
  stage: build
  script: 
    - jupyter-book build .
    - mv _build/html/* public/
  tags:
    - docker
  artifacts:
    paths:
      - public

latex:
  stage: build
  script: 
    - jupyter-book build . --builder pdflatex
    - mv _build/latex/* public/
  tags:
    - docker
  artifacts:
    paths:
      - public

linkcheck:
  stage: test
  script: 
    - jupyter-book build . --builder linkcheck
    - mv _build/html/output.txt public/
  allow_failure: true
  tags:
    - docker
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  only:
    - master
