image: pnavaro/pandoc

pages:
  stage: deploy
  script:
    - make
    - mkdir -p public
    - ~/.local/bin/jupyter-book build .
    - mv _build/html public/new
    - make html
    - mv synthese_2020.pdf public/

  tags:
    - pandoc
  artifacts:
    paths:
      - public
