image: pnavaro/pandoc

pages:
  stage: deploy
  script:
    - make
    - mkdir -p public
    - cp *.md book
    - ~/.local/bin/jupyter-book build book
    - mv book/_build/html public/jupyter-book
    - make html
    - mv synthese_2020.pdf public/

  tags:
    - pandoc
  artifacts:
    paths:
      - public
