image: pnavaro/pandoc

pages:
  stage: deploy
  script:
    - make
    - mkdir public
    - pandoc -s --toc -c pandoc.css main.md -o public/index.html
  tags:
    - pandoc, docker
  artifacts:
    paths:
      - "synthese_2020.pdf"
      - public
