image: pnavaro/pandoc

pages:
  stage: deploy
  script:
    - make
    - mkdir -p public
    - make html
    - cp synthese_2020.pdf public/

  tags:
    - pandoc
  artifacts:
    paths:
      - public
