image: pnavaro/pandoc

pages:
  stage: deploy
  script:
    - make
    - mkdir public
    - pandoc -s --toc main.md -o public/index.html
  tags:
    - pandoc
  artifacts:
    paths:
      - "synthese_2020.pdf"
      - public
