# Book settings
title: ""
author: "Atelier Données – groupe de travail inter réseaux de la MITI – CNRS"
logo: images/logo.png
copyright: "janvier 2021"

exclude_patterns: [README.md,LICENSE.md]

repository:
    url: https://gitlab.math.unistra.fr/mi-gt-donnees/guide
    branch: master

html:
    baseurl: "https://mi-gt-donnees.pages.math.unistra.fr/guide"
    use_repository_button: true
    use_edit_page_button: false
    extra_navbar: <a href="mailto:contact-guide@services.cnrs.fr">contact</a> 

parse:
  myst_extended_syntax: true

sphinx:
  config:
    language: "fr"
    html_show_copyright: true
    latex_logo: 'images/logo_small.png'
    latex_toplevel_sectioning: 'chapter'

latex:
  latex_documents:
     targetname: guide_donnees.tex
     title: "Guide de bonnes pratiques"
     author: "Atelier Données"
     theme: "manual"
