# Book settings
title: ""
author: Groupe de travail "Atelier Données"
logo: images/logo.png

exclude_patterns: [README.md,LICENSE.md,09-glossaire.md]

repository:
    url: https://gitlab.math.unistra.fr/mi-gt-donnees/synthese
    branch: master

html:
    baseurl: "https://mi-gt-donnees.pages.math.unistra.fr/synthese"
    use_repository_button: true
    use_edit_page_button: false

parse:
  myst_extended_syntax: true

sphinx:
  config:
    language: 'fr'
    latex_logo: 'images/logo_small.png'
    latex_toplevel_sectioning: 'chapter'

latex:
  latex_documents:
     targetname: guide_donnees.tex
     title: "Guide de bonnes pratiques"
     author: "Atelier Données"
     theme: "manual"
