site_name: Synthese

use_directory_urls: false

theme:
    name: mkdocs

nav:
    - Imaginer: 1.imaginer.md
    - Concevoir: 2.concevoir_planifier.md
    - Collecter: 3.collecter.md
    - Traiter: 4.traiter.md
    - Analyser: 5.analyser.md
    - Archiver: 6.archiver.md
    - Publier: 7.publier.md
    - Conclusion Bibliographie: 8.conclusion.md
    - Glossaire: 81.Glossaire.md
    - Crédits: 82.Credits.md
    - Infrastructures: 98.Infrastructures.md
    - Reproductibilité: 99.Reproductibilite.md 


markdown_extensions:
    - footnotes

plugins:
    - search
    - enumerate-headings:
