site_name: Synthese

theme:
    name: mkdocs

nav:
    - Imaginer: 1.imaginer.md
    - Concevoir: 2.concevoir_planifier.md
    - Collecter: 3.collecter.md
    - Traiter: 4.traiter.md
    - Analyser: 5.analyser.md
    - Archiver: 6.archiver.md
    - Publier: 7.publier.md
    - Conclusion Bibliographie: 8.conclusion.md

lang:
    default: ['fr']

markdown_extensions:
    - footnotes

plugins:
    - search
    - mkdocs-add-number-plugin 
