# Book settings
title: ""
author: Groupe de travail "Atelier Données"
logo: logo.png

exclude_patterns: [README.md,81.Glossaire.md]

repository:
    url: https://gitlab.math.unistra.fr/mi-gt-donnees/synthese
    branch: master

html:
    baseurl: "https://mi-gt-donnees.pages.math.unistra.fr/synthese"
    use_repository_button: true
    use_edit_page_button: false

parse:
  myst_extended_syntax: true
